#
server:
  port: 7400
#
logging:
  config: classpath:logback.xml
#
spring:
  application:
    name: study-springcloud-consumer-rest
  main:
    web-application-type: servlet
    banner-mode: off
  profiles:
    active:  @env@
#    active:  @env@, ribbon
#    active: @env@, ribbon, hystrix
#
eureka:
  instance:
    hostname: ${spring.application.name}
    ip-address: 150.158.110.15
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: @eureka.server.list@
    enabled: true
    register-with-eureka: true
    fetch-registry: true
