#
server:
  port: 7300
#
logging:
  config: classpath:logback.xml
#
spring:
  application:
    name: study-springcloud-client-rest
  main:
    web-application-type: servlet
  cloud:
    loadbalancer:
      retry:
        enabled: true
#########################
#（★）Eureka Client
#########################
eureka:
  instance:
    #hostname: study-springcloud-consumer
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: false
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: @eureka.instance.defaultZone@
#########################
#（★）Ribbon
#########################
#（1）全局配置
ribbon:
  #（▲）集成Eureka配置
  eureka:
    #禁用Eureka，禁用之后不能使用服务名调用，必须指定服务地址
    enabled: true
  #（▲）饥饿加载配置
  eager-load:
    #是否开启饥饿加载模式，默认false
    enabled: true
    #指定需要饥饿加载的服务，逗号隔开
    clients: study-springcloud-provider
  #（▲）超时设置
  #请求连接超时时间，单位ms
  ConnectTimeout: 250
  #请求处理超时时间，单位ms
  ReadTimeout: 1000
  #（▲）并发设置
  #最大连接数
  MaxTotalConnections: 500
  #每个host最大连接数
  MaxConnectionsPerHost: 500
  #（▲）重试配置
  #对当前实例的重试次数
  MaxAutoRetries: 1
  #切换实例的重试次数
  MaxAutoRetriesNextServer: 2
  #对所有操作请求都进行重试
  OkToRetryOnAllOperations: true
  #对Http响应码进行重试
  retryableStatusCodes: 404,500,502
  #NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
#（2）特定Client配置
#study-springcloud-provider:
#  ribbon:
#    #负载均衡器操作接口（ILoadBalancer）
#    NFLoadBalancerClassName: com.netflix.loadbalancer.ZoneAwareLoadBalancer
#    #负载均衡算法（IRule）
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
#    #服务可用性检查（IPing）
#    NFLoadBalancerPingClassName: com.netflix.loadbalancer.PingUrl
#    #服务实例清单维护机制，服务列表获取（ServerList）
#    NIWSServerListClassName:
#    #服务清单过滤机制，服务列表的过滤（ServerListFilter）
#    NIWSServerListFilterClassName: com.netflix.loadbalancer.ServerListSubsetFilter
