###
server:
  address: 127.0.0.1
  port: 9000
###
logging:
  config: classpath:logback.xml
###
spring:
  application:
    name: springcloud-consumer
###
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7000/eureka/
