#
server:
  port: 7080
#
logging:
  config: classpath:logback.xml
#
spring:
  application:
    name: study-springcloud-consumer
  main:
    web-application-type: servlet
#########################
#（★）Eureka Client
#########################
eureka:
  instance:
    hostname: study-springcloud-consumer
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://114.67.102.8:7101/eureka
#########################
#（★）
#########################
