########## Config Start ##########
###
server:
  address: 127.0.0.1
  port: 9000
###
spring:
  application:
    name: spring-boot-consumer
###
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://127.0.0.1:7000/eureka/
feign:
  hystrix:
    enabled: true
###
logging:
  config: classpath:logback.xml
########## Cofig End ##########
