#
server:
  port: 7400
#
logging:
  config: classpath:logback.xml
#
spring:
  application:
    name: study-springcloud-client-rest
  main:
    web-application-type: servlet
  profiles:
    active: ribbon
#******************************
#（★）Eureka Client
#******************************
eureka:
  instance:
    hostname: study-springcloud-client-rest
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: @eureka.server.list@
    #
    registry-fetch-interval-seconds: 30

