#
server:
  port: 7080
#
logging:
  config: classpath:logback.xml
#
spring:
  application:
    name: study-springcloud-consumer

#
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://114.67.102.8:7010/eureka/
# 负责均衡
#ribbon:
#  eager-load:
#    clients:

# 熔断
